@include('layout.header')
@include('layout.contact_title')
@include('layout.contact_top')
@include('layout.contact_block')
@include('layout.contact_form')
@include('layout.map')
@include('layout.footer')